const STRING = {
  BUTTON: {
    OK: "Ok",
    SEARCH: "Search",
    SUBMIT: "Submit",
    SEE_MORE: "See More",
    CHOOSE_PLAN: "Choose Plan",
    UPDATE: "Update",
    EDIT_PROFILE: "Edit Profile",
    UPDATE_LOCATION: "Update Location",
    HOME_LOCATION: "Home Location",
    CURRENT_LOCATION: "Current Location",
    LOGIN: "Login",
    SEND_OTP: "Send OTP",
    LOGIN_WITH_EMAIL: "Login with Email",
    REGISTER: "Register",
    VERIFY: "Verify",
    CLICK_TO_UPDATE: "Click to Update",
    LOGOUT: "Logout  ",
  },
  SCREEN: {
    ROOT: "Root",
    HOME: "Home",
    PRICING: "Pricing",
    CONTACT_US: "Contact Us",
    EMERGENCY: "Emergency",
    WEATHER: "Weather",
    PROFILE: "Profile",
    PROFILE_VIEW: "ProfileView",
    BUS_TIMINGS: "BusTimings",
    CATEGORY_PROJECTS: "CategoryProjects",
    EXPLORE: "Explore",
    EXPLOREGRID: "ExploreGrid",
    MAP_SCREEN: "MapScreen",
    CITIES: "Cities",
    ROUTES: "Routes",
    PLACES: "Places",
    MAP: "Map",

    LOGIN: "Login",
    SIGN_UP: "SignUp",
    EMAIL_SIGN_IN: "EmailSignIn",
    VERIFY_OTP: "VerifyOTP",

    SEARCH: "Search",
    SEARCH_PLACE: "SearchPlace",
    CITY_PLACE_SEARCH: "CityPlaceSearch",

    ROUTES_LIST: "RoutesList",
    SEARCH_LIST: "SearchList",
    ROUTES_LIST: "RoutesList",
    CITY_LIST: "CityList",
    PROJECT_LIST: "ProjectList",
    STOP_LIST: "StopList",

    PLACE_DETAILS: "PlaceDetails",
    PROJECT_DETAILS: "ProjectDetails",
    STOP_DETAILS: "StopDetails",
    CITY_DETAILS: "CityDetails",
  },
  STORAGE: {
    ACCESS_TOKEN: "access_token",
    ADDRESS: "address",
    USER_ID: "userId",
    USER_NAME: "userName",
    IS_FIRST_TIME: "isFirstTime",
    API_TOKEN: "apiToken",
    LANDING_RESPONSE: "landingResponse",
    PROFILE_RESPONSE: "profileResponse",
    CITIES_RESPONSE: "citiesResponse",
    PLACES_RESPONSE: "placesResponse",
    ROUTES_RESPONSE: "routesResponse"
  },
  HEADER: {
    BUS_TIMINGS: "Bus Timings",
    CONTACT_US: "Contact Us",
    PRICING: "Pricing",
    VERIFY_OTP: "Verify OTP",
    CITY: "City",
    PLACE: "Place",
    CITIES: "Cities",
    EXPLORE: "Explore",
    PLACE_CATEGORIES: "Place Categories",
    PROJECTS: "Projects",
    ROUTE: "Route",
    ROUTES: "Routes",
    STOPS: "Stops",
  },
  ALERT: {
    FAILED: "Failed",
    WENT_WRONG: "Something went wrong...",
    REGI_SUCCESS: "Registration Successful, now login to continue...",
    SOURCE_DESTINATION_REQUIRED: "Source & Destination are required for a Search",
    ADDING_SOON: "We are adding new places inside this category soon..!",
    LOADING: "Loading...",
    ERROR_CURRENT_LOCATION: "Error getting current location: ",
  },
  TABLE: {
    CITY: "City",
    PLACE: "Place",
    CITIES: "cities",
    PLACES: "places",
  },
  CITY: {
    DEVGAD: "Devgad",
    KANKAVLI: "Kankavli",
    MAHARASHTRA: "Maharashtra",
  },
  TYPE: {
    TEXT: "text",
    PASSWORD: "password",
    NUM: "num",
    PHONE: "phone",
    EMAIL: "email",
    PHOTO: 'photo',
    DROP_DWN: "dropDwn",
  },
  PLACEHOLDER: {
    ENTER_TEXT: "Enter Text",
    ENTER_OTP: "Enter OTP",
    MOBILE_NUMBER: "Mobile Number",
    SEARCH_SOURCE: "Search Source Stop",
    SEARCH_DESTINATION: "Search Destination Stop",
    SEARCH_CITY_PLACE: "Search for city, place",
  },
  LABEL: {
    SOURCE: "Source",
    DESTINATION: "Destination",
    MOBILE: "Mobile",
    PASSWORD: "Password",
    EMAIL: "Email",
    NAME: "Name",
    OTP: "OTP",
    CONFIRM_PASSWORD: "Confirm Password",
    CITY_NAME: "City Name",
    MESSAGE: "Message"
  },
  EVENT: {
    HARDWARE_BACK_PRESS: "hardwareBackPress",
    FOCUS: "focus",
  },

  PRESS_BACK: "Press back again to exit",
  OTP_VERIFICATION: "OTP Verification",
  WE_HAVE_SENT: "We have sent an OTP to verify your phone number.",
  SENT_TO: "Sent to +91",
  RESEND_WITHIN: "You can resend your OTP within (00:",
  DIDNT_RECEIVE: "I didn't receive a code",
  HAVE_ACC: "Already have an Account? ",
  DONT_HAVE_ACC: "Don't have an Account? ",
  SIGN_IN: " Sign-in",
  SIGN_UP: " Sign-up",
  RESEND: "Resend",
  COMING_SOON: "Coming Soon...",
  NON_RESERVATION: "Non Reservation",
  STOPS: "Stops",
  LOCATION_ACCESS_REQUIRED: "Location Access Required",
  NEEDS_TO_ACCESS: "This App needs to Access your location",
  PERMISSION_DENIED: "Permission Denied",
  GETTING_LOCATION: "Getting Location ...",
  YOU_ARE_HERE: "You are Here",
  GRANTED: "granted",
  GOOGLE_API_KEY: "AIzaSyCUUzdHc1ccGZhOzia9NoPf8mf3Yv901ZQ",
  SEARCH_FOR_AREA: "Search for area, street name...",
  USE_CURRENT_LOCATION: "Use Current Location",
  RECENT_LOCATION: "Recent Location",
  OR: "---------- OR ----------",
  ROLE: "Role",
  SELECT_ROLE: "Select Role",
  TO_EXPLORE: "Lot more to Explore...",
  TEST_MARKER: "Test Marker",
  MARKER_DESCRIPTION: "This is a description of the marker",
  ETA: "ETA: ",
  ETD: "ETD: ",
  NO_ROUTES: "No Routes Available",
  SET_LOCATION: "Set Your Primary Location",
  NO_INTERNET: "Please check your connectivity... Once data is synced you can use offline.",
  LOADER_TEXT: "Picking Up Your Data..."
};

export default STRING;
